"""add_icone_to_categorias

Revision ID: 28ba243136e8
Revises: dd1a552aec6a
Create Date: 2026-05-01 19:56:11.122095

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28ba243136e8'
down_revision = 'dd1a552aec6a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categoria', schema=None) as batch_op:
        batch_op.add_column(sa.Column('icone', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categoria', schema=None) as batch_op:
        batch_op.drop_column('icone')

    # ### end Alembic commands ###
