"""add financiamento_parcela_id to movimento_financeiro

Revision ID: 9b8a09ecc52f
Revises: c8d9e0f1a2b3
Create Date: 2026-05-11 19:31:04.895093

SUPABASE-MIGRATE-1: varios drop_index/drop_constraint/drop_table nesta
migration assumem objetos criados fora do Alembic (drift local anterior
ao baseline dd1a552aec6a — provavelmente db.create_all() num ponto
antigo do projeto). Em um banco criado do zero (ex.: Supabase), esses
objetos nunca existiram, e os drops originais falhavam. Trocados por
checagens de existencia via inspector antes de cada drop, preservando
o comportamento em bancos onde o objeto existe (drop de verdade) e
tornando a migration idempotente onde nao existe (no-op). Os
create_index/create_foreign_key/alter_column nao foram alterados —
sao seguros de rodar contra uma tabela recem-criada.
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9b8a09ecc52f'
down_revision = 'c8d9e0f1a2b3'
branch_labels = None
depends_on = None


def _indice_existe(inspector, tabela, nome_indice):
    return any(idx['name'] == nome_indice for idx in inspector.get_indexes(tabela))


def _fk_existe(inspector, tabela, nome_fk):
    return any(fk['name'] == nome_fk for fk in inspector.get_foreign_keys(tabela))


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    if 'categoria_cartao_mapeamento' in inspector.get_table_names():
        with op.batch_alter_table('categoria_cartao_mapeamento', schema=None) as batch_op:
            batch_op.drop_index(batch_op.f('ix_categoria_cartao_mapeamento_cartao'))
            batch_op.drop_index(batch_op.f('ix_categoria_cartao_mapeamento_categoria'))
            batch_op.drop_index(batch_op.f('ix_categoria_cartao_mapeamento_item_agregado'))

        op.drop_table('categoria_cartao_mapeamento')

    with op.batch_alter_table('cartao_categoria_limite', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.create_index(batch_op.f('ix_cartao_categoria_limite_perfil_financeiro_id'), ['perfil_financeiro_id'], unique=False)

    with op.batch_alter_table('categoria', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_categoria_perfil_financeiro_id'), ['perfil_financeiro_id'], unique=False)

    with op.batch_alter_table('categoria_cartao', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.create_index(batch_op.f('ix_categoria_cartao_perfil_financeiro_id'), ['perfil_financeiro_id'], unique=False)

    with op.batch_alter_table('categoria_cartao_despesa', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        if _indice_existe(inspector, 'categoria_cartao_despesa', 'ux_categoria_cartao_despesa_categoria_ativa'):
            batch_op.drop_index(batch_op.f('ux_categoria_cartao_despesa_categoria_ativa'), postgresql_where='ativo')
        batch_op.create_index(batch_op.f('ix_categoria_cartao_despesa_perfil_financeiro_id'), ['perfil_financeiro_id'], unique=False)

    with op.batch_alter_table('conta', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_conta_perfil_financeiro_id'), ['perfil_financeiro_id'], unique=False)

    with op.batch_alter_table('conta_bancaria', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_conta_bancaria_perfil_financeiro_id'), ['perfil_financeiro_id'], unique=False)

    with op.batch_alter_table('conta_patrimonio', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_conta_patrimonio_perfil_financeiro_id'), ['perfil_financeiro_id'], unique=False)

    with op.batch_alter_table('despesa_prevista', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_despesa_prevista_perfil_financeiro_id'), ['perfil_financeiro_id'], unique=False)

    with op.batch_alter_table('financiamento', schema=None) as batch_op:
        if _indice_existe(inspector, 'financiamento', 'idx_financiamento_perfil_ativo'):
            batch_op.drop_index(batch_op.f('idx_financiamento_perfil_ativo'))
        batch_op.create_index(batch_op.f('ix_financiamento_perfil_financeiro_id'), ['perfil_financeiro_id'], unique=False)

    with op.batch_alter_table('financiamento_amortizacao_extra', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_financiamento_amortizacao_extra_perfil_financeiro_id'), ['perfil_financeiro_id'], unique=False)

    # financiamento_documento.parcela_id/amortizacao_id/ajuste_saldo_id
    # nunca foram adicionadas por nenhuma migration (drift local pre-Alembic).
    colunas_fin_doc = {c['name'] for c in inspector.get_columns('financiamento_documento')}
    with op.batch_alter_table('financiamento_documento', schema=None) as batch_op:
        if 'amortizacao_id' not in colunas_fin_doc:
            batch_op.add_column(sa.Column('amortizacao_id', sa.Integer(), nullable=True))
        if 'parcela_id' not in colunas_fin_doc:
            batch_op.add_column(sa.Column('parcela_id', sa.Integer(), nullable=True))
        if 'ajuste_saldo_id' not in colunas_fin_doc:
            batch_op.add_column(sa.Column('ajuste_saldo_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'financiamento_amortizacao_extra', ['amortizacao_id'], ['id'])
        batch_op.create_foreign_key(None, 'financiamento_parcela', ['parcela_id'], ['id'])
        batch_op.create_foreign_key(None, 'financiamento_ajuste_saldo', ['ajuste_saldo_id'], ['id'])

    with op.batch_alter_table('financiamento_parcela', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_financiamento_parcela_perfil_financeiro_id'), ['perfil_financeiro_id'], unique=False)

    with op.batch_alter_table('financiamento_seguro_vigencia', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_financiamento_seguro_vigencia_perfil_financeiro_id'), ['perfil_financeiro_id'], unique=False)

    with op.batch_alter_table('ir_categoria_despesa', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ir_categoria_despesa_perfil_financeiro_id'), ['perfil_financeiro_id'], unique=False)

    with op.batch_alter_table('ir_comprovante', schema=None) as batch_op:
        if _indice_existe(inspector, 'ir_comprovante', 'ix_ir_comprovante_hash_arquivo'):
            batch_op.drop_index(batch_op.f('ix_ir_comprovante_hash_arquivo'))
        batch_op.create_index(batch_op.f('ix_ir_comprovante_hash_arquivo'), ['hash_arquivo'], unique=False)
        batch_op.create_index(batch_op.f('ix_ir_comprovante_perfil_financeiro_id'), ['perfil_financeiro_id'], unique=False)

    with op.batch_alter_table('item_despesa', schema=None) as batch_op:
        if _indice_existe(inspector, 'item_despesa', 'idx_item_despesa_origem'):
            batch_op.drop_index(batch_op.f('idx_item_despesa_origem'), postgresql_where='(origem_tipo IS NOT NULL)')
        batch_op.create_index(batch_op.f('ix_item_despesa_perfil_financeiro_id'), ['perfil_financeiro_id'], unique=False)
        if _fk_existe(inspector, 'item_despesa', 'item_despesa_categoria_cartao_id_fkey'):
            batch_op.drop_constraint(batch_op.f('item_despesa_categoria_cartao_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'categoria_cartao', ['categoria_cartao_id'], ['id'])

    with op.batch_alter_table('item_receita', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_item_receita_perfil_financeiro_id'), ['perfil_financeiro_id'], unique=False)

    with op.batch_alter_table('lancamento_agregado', schema=None) as batch_op:
        if _indice_existe(inspector, 'lancamento_agregado', 'ix_lanc_agregado_categoria_cartao_fatura'):
            batch_op.drop_index(batch_op.f('ix_lanc_agregado_categoria_cartao_fatura'))
        batch_op.create_index('idx_lanc_agregado_categoria_cartao_fatura', ['categoria_cartao_id', 'mes_fatura'], unique=False)
        batch_op.create_index(batch_op.f('ix_lancamento_agregado_perfil_financeiro_id'), ['perfil_financeiro_id'], unique=False)

    with op.batch_alter_table('mobilidade_assinatura', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
        if _indice_existe(inspector, 'mobilidade_assinatura', 'idx_mob_assinatura_perfil_status'):
            batch_op.drop_index(batch_op.f('idx_mob_assinatura_perfil_status'))
        if _indice_existe(inspector, 'mobilidade_assinatura', 'idx_mob_assinatura_status'):
            batch_op.drop_index(batch_op.f('idx_mob_assinatura_status'), postgresql_where="((status)::text = 'ATIVO'::text)")
        batch_op.create_index(batch_op.f('ix_mobilidade_assinatura_perfil_financeiro_id'), ['perfil_financeiro_id'], unique=False)
        if _fk_existe(inspector, 'mobilidade_assinatura', 'mobilidade_assinatura_categoria_id_fkey'):
            batch_op.drop_constraint(batch_op.f('mobilidade_assinatura_categoria_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'categoria', ['categoria_id'], ['id'])

    with op.batch_alter_table('mobilidade_cenario_ativo', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
        if _indice_existe(inspector, 'mobilidade_cenario_ativo', 'idx_mob_cenario_perfil_status'):
            batch_op.drop_index(batch_op.f('idx_mob_cenario_perfil_status'))
        if _indice_existe(inspector, 'mobilidade_cenario_ativo', 'idx_mob_cenario_status'):
            batch_op.drop_index(batch_op.f('idx_mob_cenario_status'), postgresql_where="((status)::text = 'ATIVO'::text)")
        batch_op.create_index(batch_op.f('ix_mobilidade_cenario_ativo_perfil_financeiro_id'), ['perfil_financeiro_id'], unique=False)
        if _fk_existe(inspector, 'mobilidade_cenario_ativo', 'mobilidade_cenario_ativo_cartao_id_fkey'):
            batch_op.drop_constraint(batch_op.f('mobilidade_cenario_ativo_cartao_id_fkey'), type_='foreignkey')
        if _fk_existe(inspector, 'mobilidade_cenario_ativo', 'mobilidade_cenario_ativo_categoria_id_fkey'):
            batch_op.drop_constraint(batch_op.f('mobilidade_cenario_ativo_categoria_id_fkey'), type_='foreignkey')
        if _fk_existe(inspector, 'mobilidade_cenario_ativo', 'mobilidade_cenario_ativo_categoria_cartao_id_fkey'):
            batch_op.drop_constraint(batch_op.f('mobilidade_cenario_ativo_categoria_cartao_id_fkey'), type_='foreignkey')
        if _fk_existe(inspector, 'mobilidade_cenario_ativo', 'mobilidade_cenario_ativo_recorrencia_id_fkey'):
            batch_op.drop_constraint(batch_op.f('mobilidade_cenario_ativo_recorrencia_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'item_despesa', ['recorrencia_id'], ['id'])
        batch_op.create_foreign_key(None, 'item_despesa', ['cartao_id'], ['id'])
        batch_op.create_foreign_key(None, 'categoria', ['categoria_id'], ['id'])
        batch_op.create_foreign_key(None, 'categoria_cartao', ['categoria_cartao_id'], ['id'])

    with op.batch_alter_table('movimento_financeiro', schema=None) as batch_op:
        batch_op.add_column(sa.Column('financiamento_parcela_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_movimento_financiamento_parcela', 'financiamento_parcela', ['financiamento_parcela_id'], ['id'])
        batch_op.create_index('idx_movimento_financiamento_parcela', ['financiamento_parcela_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_movimento_financeiro_perfil_financeiro_id'), ['perfil_financeiro_id'], unique=False)

    with op.batch_alter_table('receita_orcamento', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_receita_orcamento_perfil_financeiro_id'), ['perfil_financeiro_id'], unique=False)

    with op.batch_alter_table('receita_realizada', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_receita_realizada_perfil_financeiro_id'), ['perfil_financeiro_id'], unique=False)

    with op.batch_alter_table('transferencia', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_transferencia_perfil_financeiro_id'), ['perfil_financeiro_id'], unique=False)

    with op.batch_alter_table('veiculo', schema=None) as batch_op:
        if _indice_existe(inspector, 'veiculo', 'idx_veiculo_perfil_status'):
            batch_op.drop_index(batch_op.f('idx_veiculo_perfil_status'))
        batch_op.create_index(batch_op.f('ix_veiculo_perfil_financeiro_id'), ['perfil_financeiro_id'], unique=False)

    with op.batch_alter_table('veiculo_ciclo_manutencao', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_veiculo_ciclo_manutencao_perfil_financeiro_id'), ['perfil_financeiro_id'], unique=False)

    with op.batch_alter_table('veiculo_financiamento', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_veiculo_financiamento_perfil_financeiro_id'), ['perfil_financeiro_id'], unique=False)

    with op.batch_alter_table('veiculo_regra_manutencao_km', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_veiculo_regra_manutencao_km_perfil_financeiro_id'), ['perfil_financeiro_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('veiculo_regra_manutencao_km', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_veiculo_regra_manutencao_km_perfil_financeiro_id'))

    with op.batch_alter_table('veiculo_financiamento', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_veiculo_financiamento_perfil_financeiro_id'))

    with op.batch_alter_table('veiculo_ciclo_manutencao', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_veiculo_ciclo_manutencao_perfil_financeiro_id'))

    with op.batch_alter_table('veiculo', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_veiculo_perfil_financeiro_id'))
        batch_op.create_index(batch_op.f('idx_veiculo_perfil_status'), ['perfil_financeiro_id', 'status'], unique=False)

    with op.batch_alter_table('transferencia', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transferencia_perfil_financeiro_id'))

    with op.batch_alter_table('receita_realizada', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_receita_realizada_perfil_financeiro_id'))

    with op.batch_alter_table('receita_orcamento', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_receita_orcamento_perfil_financeiro_id'))

    with op.batch_alter_table('movimento_financeiro', schema=None) as batch_op:
        batch_op.drop_index('idx_movimento_financiamento_parcela')
        batch_op.drop_constraint('fk_movimento_financiamento_parcela', type_='foreignkey')
        batch_op.drop_column('financiamento_parcela_id')
        batch_op.drop_index(batch_op.f('ix_movimento_financeiro_perfil_financeiro_id'))

    with op.batch_alter_table('mobilidade_cenario_ativo', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('mobilidade_cenario_ativo_recorrencia_id_fkey'), 'item_despesa', ['recorrencia_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(batch_op.f('mobilidade_cenario_ativo_categoria_cartao_id_fkey'), 'categoria_cartao', ['categoria_cartao_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(batch_op.f('mobilidade_cenario_ativo_categoria_id_fkey'), 'categoria', ['categoria_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(batch_op.f('mobilidade_cenario_ativo_cartao_id_fkey'), 'item_despesa', ['cartao_id'], ['id'], ondelete='SET NULL')
        batch_op.drop_index(batch_op.f('ix_mobilidade_cenario_ativo_perfil_financeiro_id'))
        batch_op.create_index(batch_op.f('idx_mob_cenario_status'), ['status'], unique=False, postgresql_where="((status)::text = 'ATIVO'::text)")
        batch_op.create_index(batch_op.f('idx_mob_cenario_perfil_status'), ['perfil_financeiro_id', 'status'], unique=False)
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))

    with op.batch_alter_table('mobilidade_assinatura', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('mobilidade_assinatura_categoria_id_fkey'), 'categoria', ['categoria_id'], ['id'], ondelete='SET NULL')
        batch_op.drop_index(batch_op.f('ix_mobilidade_assinatura_perfil_financeiro_id'))
        batch_op.create_index(batch_op.f('idx_mob_assinatura_status'), ['status'], unique=False, postgresql_where="((status)::text = 'ATIVO'::text)")
        batch_op.create_index(batch_op.f('idx_mob_assinatura_perfil_status'), ['perfil_financeiro_id', 'status'], unique=False)
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))

    with op.batch_alter_table('lancamento_agregado', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lancamento_agregado_perfil_financeiro_id'))
        batch_op.drop_index('idx_lanc_agregado_categoria_cartao_fatura')
        batch_op.create_index(batch_op.f('ix_lanc_agregado_categoria_cartao_fatura'), ['categoria_cartao_id', 'mes_fatura'], unique=False)

    with op.batch_alter_table('item_receita', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_item_receita_perfil_financeiro_id'))

    with op.batch_alter_table('item_despesa', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('item_despesa_categoria_cartao_id_fkey'), 'categoria_cartao', ['categoria_cartao_id'], ['id'], ondelete='SET NULL')
        batch_op.drop_index(batch_op.f('ix_item_despesa_perfil_financeiro_id'))
        batch_op.create_index(batch_op.f('idx_item_despesa_origem'), ['origem_tipo', 'origem_id'], unique=False, postgresql_where='(origem_tipo IS NOT NULL)')

    with op.batch_alter_table('ir_comprovante', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ir_comprovante_perfil_financeiro_id'))
        batch_op.drop_index(batch_op.f('ix_ir_comprovante_hash_arquivo'))
        batch_op.create_index(batch_op.f('ix_ir_comprovante_hash_arquivo'), ['hash_arquivo'], unique=True)

    with op.batch_alter_table('ir_categoria_despesa', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ir_categoria_despesa_perfil_financeiro_id'))

    with op.batch_alter_table('financiamento_seguro_vigencia', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_financiamento_seguro_vigencia_perfil_financeiro_id'))

    with op.batch_alter_table('financiamento_parcela', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_financiamento_parcela_perfil_financeiro_id'))

    with op.batch_alter_table('financiamento_documento', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('financiamento_amortizacao_extra', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_financiamento_amortizacao_extra_perfil_financeiro_id'))

    with op.batch_alter_table('financiamento', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_financiamento_perfil_financeiro_id'))
        batch_op.create_index(batch_op.f('idx_financiamento_perfil_ativo'), ['perfil_financeiro_id', 'ativo'], unique=False)

    with op.batch_alter_table('despesa_prevista', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_despesa_prevista_perfil_financeiro_id'))

    with op.batch_alter_table('conta_patrimonio', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_conta_patrimonio_perfil_financeiro_id'))

    with op.batch_alter_table('conta_bancaria', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_conta_bancaria_perfil_financeiro_id'))

    with op.batch_alter_table('conta', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_conta_perfil_financeiro_id'))

    with op.batch_alter_table('categoria_cartao_despesa', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_categoria_cartao_despesa_perfil_financeiro_id'))
        batch_op.create_index(batch_op.f('ux_categoria_cartao_despesa_categoria_ativa'), ['categoria_id'], unique=True, postgresql_where='ativo')
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))

    with op.batch_alter_table('categoria_cartao', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_categoria_cartao_perfil_financeiro_id'))
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))

    with op.batch_alter_table('categoria', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_categoria_perfil_financeiro_id'))

    with op.batch_alter_table('cartao_categoria_limite', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cartao_categoria_limite_perfil_financeiro_id'))
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))

    op.create_table('categoria_cartao_mapeamento',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('cartao_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('categoria_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('item_agregado_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('ativo', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['cartao_id'], ['item_despesa.id'], name=op.f('categoria_cartao_mapeamento_cartao_id_fkey')),
    sa.ForeignKeyConstraint(['categoria_id'], ['categoria.id'], name=op.f('categoria_cartao_mapeamento_categoria_id_fkey')),
    sa.ForeignKeyConstraint(['item_agregado_id'], ['item_agregado.id'], name=op.f('categoria_cartao_mapeamento_item_agregado_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('categoria_cartao_mapeamento_pkey')),
    sa.UniqueConstraint('cartao_id', 'categoria_id', name=op.f('ux_categoria_cartao_mapeamento_cartao_categoria'))
    )
    with op.batch_alter_table('categoria_cartao_mapeamento', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_categoria_cartao_mapeamento_item_agregado'), ['item_agregado_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_categoria_cartao_mapeamento_categoria'), ['categoria_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_categoria_cartao_mapeamento_cartao'), ['cartao_id'], unique=False)

    # ### end Alembic commands ###
