"""add_logo_fields_to_categorias

Revision ID: ea039138b34d
Revises: 28ba243136e8
Create Date: 2026-05-01 22:47:02.092855

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea039138b34d'
down_revision = '28ba243136e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categoria', schema=None) as batch_op:
        batch_op.add_column(sa.Column('logo_arquivo', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('logo_mime', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('logo_tamanho', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('logo_original_nome', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('logo_criado_em', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categoria', schema=None) as batch_op:
        batch_op.drop_column('logo_criado_em')
        batch_op.drop_column('logo_original_nome')
        batch_op.drop_column('logo_tamanho')
        batch_op.drop_column('logo_mime')
        batch_op.drop_column('logo_arquivo')

    # ### end Alembic commands ###
