"""Adicionar campos data_validade e tem_codigo em ConfigAgregador

Revision ID: 4926ed11c8bb
Revises: 
Create Date: 2025-12-01 17:27:50.427581

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4926ed11c8bb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('config_agregador', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data_validade', sa.String(length=7), nullable=True))
        batch_op.add_column(sa.Column('tem_codigo', sa.Boolean(), nullable=True))

    with op.batch_alter_table('item_despesa', schema=None) as batch_op:
        batch_op.alter_column('categoria_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item_despesa', schema=None) as batch_op:
        batch_op.alter_column('categoria_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('config_agregador', schema=None) as batch_op:
        batch_op.drop_column('tem_codigo')
        batch_op.drop_column('data_validade')

    # ### end Alembic commands ###
