"""Expandir módulo de receitas com novos campos e funcionalidades

Revision ID: b60e2da6e02c
Revises: 4926ed11c8bb
Create Date: 2025-12-02 00:20:10.847365

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b60e2da6e02c'
down_revision = '4926ed11c8bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item_receita', schema=None) as batch_op:
        batch_op.add_column(sa.Column('valor_base_mensal', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('dia_previsto_pagamento', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('conta_origem_id', sa.Integer(), nullable=True))
        batch_op.alter_column('tipo',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=30),
               existing_nullable=False)
        batch_op.create_foreign_key('fk_item_receita_conta_patrimonio', 'conta_patrimonio', ['conta_origem_id'], ['id'])

    with op.batch_alter_table('receita_orcamento', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ano_mes', sa.Date(), nullable=False))
        batch_op.add_column(sa.Column('valor_previsto', sa.Numeric(precision=10, scale=2), nullable=False))
        batch_op.add_column(sa.Column('periodicidade', sa.String(length=20), nullable=True))
        batch_op.drop_index(batch_op.f('idx_rec_orc_item_mes'))
        batch_op.create_index('idx_rec_orc_item_mes', ['item_receita_id', 'ano_mes'], unique=False)
        batch_op.drop_column('mes_referencia')
        batch_op.drop_column('valor_esperado')

    with op.batch_alter_table('receita_realizada', schema=None) as batch_op:
        batch_op.add_column(sa.Column('valor_recebido', sa.Numeric(precision=10, scale=2), nullable=False))
        batch_op.add_column(sa.Column('competencia', sa.Date(), nullable=False))
        batch_op.add_column(sa.Column('conta_origem_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('orcamento_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('atualizado_em', sa.DateTime(), nullable=True))
        batch_op.drop_index(batch_op.f('idx_rec_real_item_mes'))
        batch_op.create_index('idx_rec_real_competencia', ['competencia'], unique=False)
        batch_op.create_index('idx_rec_real_item_comp', ['item_receita_id', 'competencia'], unique=False)
        batch_op.create_foreign_key('fk_receita_realizada_orcamento', 'receita_orcamento', ['orcamento_id'], ['id'])
        batch_op.create_foreign_key('fk_receita_realizada_conta_patrimonio', 'conta_patrimonio', ['conta_origem_id'], ['id'])
        batch_op.drop_column('mes_referencia')
        batch_op.drop_column('valor')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('receita_realizada', schema=None) as batch_op:
        batch_op.add_column(sa.Column('valor', sa.NUMERIC(precision=10, scale=2), nullable=False))
        batch_op.add_column(sa.Column('mes_referencia', sa.DATE(), nullable=False))
        batch_op.drop_constraint('fk_receita_realizada_conta_patrimonio', type_='foreignkey')
        batch_op.drop_constraint('fk_receita_realizada_orcamento', type_='foreignkey')
        batch_op.drop_index('idx_rec_real_item_comp')
        batch_op.drop_index('idx_rec_real_competencia')
        batch_op.create_index(batch_op.f('idx_rec_real_item_mes'), ['item_receita_id', 'mes_referencia'], unique=False)
        batch_op.drop_column('atualizado_em')
        batch_op.drop_column('orcamento_id')
        batch_op.drop_column('conta_origem_id')
        batch_op.drop_column('competencia')
        batch_op.drop_column('valor_recebido')

    with op.batch_alter_table('receita_orcamento', schema=None) as batch_op:
        batch_op.add_column(sa.Column('valor_esperado', sa.NUMERIC(precision=10, scale=2), nullable=False))
        batch_op.add_column(sa.Column('mes_referencia', sa.DATE(), nullable=False))
        batch_op.drop_index('idx_rec_orc_item_mes')
        batch_op.create_index(batch_op.f('idx_rec_orc_item_mes'), ['item_receita_id', 'mes_referencia'], unique=False)
        batch_op.drop_column('periodicidade')
        batch_op.drop_column('valor_previsto')
        batch_op.drop_column('ano_mes')

    with op.batch_alter_table('item_receita', schema=None) as batch_op:
        batch_op.drop_constraint('fk_item_receita_conta_patrimonio', type_='foreignkey')
        batch_op.alter_column('tipo',
               existing_type=sa.String(length=30),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
        batch_op.drop_column('conta_origem_id')
        batch_op.drop_column('dia_previsto_pagamento')
        batch_op.drop_column('valor_base_mensal')

    # ### end Alembic commands ###
